---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  namespace: {{YOUR_NAMESPA_CE}}
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: apiservice
  replicas: 1
  template:
    metadata:
      labels:
        name: apiservice
    spec:
      containers:
        - image: mcltn/apiservice:1.0
          name: apiservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: STATUS_SERVICE
              value: 'http://status:8080'
            - name: BOOTSTRAP_SERVERS
              value: 'kafka:9092'
---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: apiservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: courier
  replicas: 1
  template:
    metadata:
      labels:
        name: courier
    spec:
      containers:
        - image: mcltn/courierconsumer:1.0
          imagePullPolicy: Always
          name: courier
          env:
            - name: MONGODB_REPLICA_HOSTNAMES
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_HOSTNAMES
            - name: MONGODB_REPLICA_SET
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_SET
            - name: MONGODB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_DBNAME
            - name: MONGODB_AUTH_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_AUTH_DBNAME
            - name: MONGODB_CA_PATH
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_CA_PATH
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_PASSWORD
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: BOOTSTRAP_SERVERS
          volumeMounts:
            - name: icd-cert
              mountPath: /home/node/app/icd.pem
              subPath: icd.pem
              readOnly: true
      volumes:
        - name: icd-cert
          secret:
            secretName: icd-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: kitchen
  replicas: 1
  template:
    metadata:
      labels:
        name: kitchen
    spec:
      containers:
        - name: kitchen
          image: mcltn/kitchenconsumer:1.0
          imagePullPolicy: Always
          env:
            - name: MONGODB_REPLICA_HOSTNAMES
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_HOSTNAMES
            - name: MONGODB_REPLICA_SET
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_SET
            - name: MONGODB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_DBNAME
            - name: MONGODB_AUTH_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_AUTH_DBNAME
            - name: MONGODB_CA_PATH
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_CA_PATH
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_PASSWORD
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: BOOTSTRAP_SERVERS
          volumeMounts:
            - name: icd-cert
              mountPath: /home/node/app/icd.pem
              subPath: icd.pem
              readOnly: true
      volumes:
        - name: icd-cert
          secret:
            secretName: icd-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: orders
  replicas: 1
  template:
    metadata:
      labels:
        name: orders
    spec:
      containers:
        - image: mcltn/orderconsumer:1.0
          imagePullPolicy: Always
          name: orders
          env:
            - name: MONGODB_REPLICA_HOSTNAMES
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_HOSTNAMES
            - name: MONGODB_REPLICA_SET
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_REPLICA_SET
            - name: MONGODB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_DBNAME
            - name: MONGODB_AUTH_DBNAME
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_AUTH_DBNAME
            - name: MONGODB_CA_PATH
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_CA_PATH
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: MONGODB_PASSWORD
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: icd-secrets
                  key: BOOTSTRAP_SERVERS
          volumeMounts:
            - name: icd-cert
              mountPath: /home/node/app/icd.pem
              subPath: icd.pem
              readOnly: true
      volumes:
        - name: icd-cert
          secret:
            secretName: icd-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podconsumerdata
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: podconsumerdata
  replicas: 1
  template:
    metadata:
      labels:
        name: podconsumerdata
    spec:
      serviceAccountName: deployer
      imagePullSecrets:
        - name: all-icr-io
      containers:
        - image: mcltn/poddata:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          name: podconsumerdata
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: podconsumerdata
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: podconsumerdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtimedata
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: realtimedata
  replicas: 1
  template:
    metadata:
      labels:
        name: realtimedata
    spec:
      imagePullSecrets:
        - name: all-icr-io
      containers:
        - image: mcltn/realtimedata:1.0
          imagePullPolicy: Always
          name: realtimedata
          ports:
            - containerPort: 8080
          env:
            - name: BOOTSTRAP_SERVERS
              value: 'kafka:9092'
---
apiVersion: v1
kind: Service
metadata:
  name: realtimedata
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: realtimedata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  selector:
    matchLabels:
      name: status
  replicas: 1
  template:
    metadata:
      labels:
        name: status
    spec:
      containers:
        - image: mcltn/statusservice:1.0
          imagePullPolicy: Always
          name: status
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: 'redis'
            - name: REDIS_PORT
              value: '6379'
            - name: BOOTSTRAP_SERVERS
              value: 'kafka:9092'
---
apiVersion: v1
kind: Service
metadata:
  name: status
  namespace: {{YOUR_NAMESPACE}}
  labels:
    razee/watch-resource: detail
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: status
